-- 입양 시각 구하기 1.
SELECT A.HOUR, COUNT(A.HOUR) AS COUNT
FROM (
        SELECT EXTRACT(HOUR FROM CAST(datetime AS TIMESTAMP)) AS HOUR
        FROM animal_outs
     ) A
WHERE A.HOUR BETWEEN 9 AND 19
GROUP BY A.HOUR
ORDER BY A.HOUR;